### ISSUE TITLE
Expressing Interest to Contribute to "sugoi-anime" Repository

### ISSUE THREAD

**Issue by MuhammadZeeshanAshraf** [CodeNinja-tech/sugoi-anime#18]
Dear dev-xero,

I hope this email finds you well. I recently stumbled upon your GitHub repository, "sugoi-anime," and I was impressed by its mission to stream high-quality anime without ads. As an anime lover myself, I appreciate your efforts to make anime more accessible and enjoyable for everyone.

I am writing to express my interest in contributing to your project. My expertise lies in backend development with Node.js, TypeScript, and Nest.js, and I believe that I can make valuable contributions to your project in this area.

I have already forked your repository and spent some time familiarizing myself with the codebase.

I would love to discuss this further with you and see how I can contribute. Please let me know if you have any specific areas that you would like help with or if there are any guidelines I should follow when making contributions.

Thank you for your time and consideration, and I look forward to hearing back from you.

Best regards,
Zeeshan Ashraf

**Comment by dev-xero** [comment]
Thanks! I really appreciate your effort, but I've actually stopped developing this project to focus on other things. There's still a lot to be implemented though. I would recommend that you check out this [project](https://github.com/consumet/api.consumet.org). It's an API you could deploy and some fantastic people are actively maintaining it. I can send you the Figma design file if that'll be of any help. Best regards.

**Comment by dev-xero** [comment]
We could continue discussing on [Discord](https://discord.gg/qTPfvMxzNH), there're lots of great people there and I'll be archiving the project soon
